### ISSUE TITLE
Installation and Documentation?

### ISSUE THREAD

**Issue by khushit-shah** [billforsternz/thc-chess-library#1]
Hey, Is there any installation and documentation?

**Comment by billforsternz** [comment]
Sadly no. As far as "installation" is concerned, it's not really that kind of library. I found actual libraries are annoying to deploy in C++, so I reused an Idea I first saw in sqlite - the individual .cpp and .h files are concatenated into a single thc.cpp and thc.h which you can then just drop into any C++ project. There is example code in my Tarrasch chess gui project (and latterly in my simpler, smaller retro sargon project) and the various APIs are documented inline inside the source files - but sadly no standalone documentation. Sorry.

**Comment by khushit-shah** [comment]
Okay, Cool!
